java异常在平时项目开发中基本用不到，因为我开发的单体项目输入什么都是由我决定的，怎么会出现错误，但是当项目被大家所使用的时候，就要考虑到项目输入可能会出现的各种问题，结合现在各种的网络攻击对参数进行校验显得十分必要，不仅仅是在前端，在后端也是十分必要，如直接使用postman等工具躲过前端的数据校验。



## 异常基础知识

异常层次

![Java 基础篇专栏 - 异常](https://www.javazhiyin.com/wp-content/uploads/2019/11/java3-1573909458.jpg)

java中的异常主要分为两大类，主要为Error以及Exception

其中Exception 分为check异常以及uncheck异常（也就是运行异常）对于check类型异常 java编译器要求程序员必须进行处理，否则无法通过编译。



`	Error`: Java虚拟机无法解决的严重问题。如：JVM系统内部错误、资源耗尽、虚拟机错误(`VirtualMacheError`)及其子类内存溢出错误(`OutOfMemoryError`)和栈溢出错误(`StackOverflowError`)。一般不编写针对性的代码进行处理；

`Exception`: 其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如： 空指针访问、试图读取不存在的文件、网络连接中断； 异常



## 异常处理以及自定义异常

**重点** java提供的异常处理机制是**抓抛模型**

- `Java`程序的执行过程中如出现异常，会生成一个异常类对象，该异常对象将被提交给`Java`运行时系统，这个过程称为抛出(`throw`)异常。
- 异常对象的生成:
  - 由虚拟机自动生成：程序运行过程中，虚拟机检测到程序发生了问题，如果在当前代码中没有找到相应的处理程序，就会在后台自动创建一个对应异常类的实例对象并抛出 --> 自动抛出；
  - 由程序员手动创建：`Exception exception = new ClassCastException();` --> 创建好的异常对象不抛出对程序没有任何影响，和创建一个普通对象一样；
- 如果一个方法内抛出异常，该异常对象会被抛给调用者方法中处理。如果异常没有在调用者方法中处理，它继续被抛给这个调用方法的上层方法。这个过程将一直继续下去，直到异常被处理。这一过程称为捕获(`catch`)异常。如果一个异常回到`main()`方法，并且`main()`也不处理，则程序运行终止。(就是上面说的异常链)

![在这里插入图片描述](https://github.com/ZXZxin/ZXBlog/raw/master/Java/%E5%BC%82%E5%B8%B8/images/y6.png)



**Java提供的"抓抛模型"**

- `"抛"`，当我们执行代码时，一旦出现异常，就会在异常的代码出生成一个对应的异常类型的对象，并将此对象抛出(**自动抛出/手动抛出**)。
  - ① 一旦抛出此异常类的对象，那么程序就终止执行；
  - ② 此异常类的对象抛给方法的调用者；
  - ③ 异常类既可以是现成的异常类，也可以是自己创建的异常类；
- `"抓"`，抓住上一步抛出来的异常类的对象，如何抓? 即为异常的处理方式。

**"抓"的两种处理方式**

- 第一种处理的方式: `try catch`
  - ① 注意`try`内声明的变量，类似于局部变量，出了`try{}`语句，就不能被调用；
  - ② `catch`语句内部是对异常对象的处理 ，例如 `getMessage()`、`printStackTrace()`；
  - ③ 可以有多个`catch`语句，`try`中抛出的异常类对象从上往下去匹配`catch`中的异常类的类型，一旦满足就执行`catch`中的代码，执行完，就跳出其后的多条`catch`语句；
  - ④ 对于运行时异常，可以不显示的处理。对于编译时异常，必须要显示的进行处理；
  - ⑤ 若`catch`中有多个异常类型是"并列关系"，熟上熟下都可以。若是"包含"关系，必须将子类放在父类的上面，否则报错；
  - ⑥ `finally`中存放的是一定会执行的代码，不管`try`中，`catch`中是否仍有异常未处理，以及是否有`return `语句；
  - ⑦ `try - catch`是可以嵌套的；
  - ⑧ `catch`块内处理完后，可以重新抛出异常，异常可以是原来的，也可以是新建的(为什么要重新抛出呢？因为当前代码不能够完全处理该异常，需要调用者进一步处理)；
- 第二种处理的方式: `throws `(在方法的声明处，显示的抛出改异常对象的类型)
  - 当异常在一个方法内部出现的时候，会抛一个异常类的对象，抛给方法的调用者；
  - 异常的对象可以逐层向上抛，直至`main()`中，当然在向上抛的过程中，可以再通过`try-catch`进行处理；



## 异常关键字

try  catch finally 异常捕获的关键字中，catch关键字不是必须的

注意: `try/catch/finally`语法中，`catch`不是必需的，也就是可以只有`try/finally`，表示不捕获异常，异常自动向上传递，但`finally`中的代码在异常发生后也执行。

1. try代码块中 变量为局部变量  
2. finally 中产生的异常会覆盖catch中捕获的异常
3. finally中return会覆盖catch中return的内容，即以finally中return为最终值
4. 若在finally代码返回之前，语句中有return语句这时会创建一个对象副本进行保存暂时状态，待finally中代码执行完成后返回，若为引用数据类型这时finally中的修改会产生对原数据有一定影响。

例子4 [blog](https://blog.csdn.net/qq_43230540/article/details/89222509)



对于`RuntimeException`和`checked exception`区别:

- 对于`RuntimeException(unchecked exception)`，是不要求使用`throws`进行声明的，但对于`checked exception`，则必须进行声明，换句话说，如果没有声明，则不能抛出。
- 对于`checked exception`，不可以抛出而不声明，但可以声明抛出但实际不抛出，不抛出声明它干嘛？主要用于在父类方法中声明，父类方法内可能没有抛出，但子类重写方法后可能就抛出了，子类不能抛出父类方法中没有声明的`checked exception`，所以就将所有可能抛出的异常都写到父类上了

```java
  public static int  test(Integer a) throws Exception {
        Integer ret=1000;
        try {
            int b=a/0;
        }catch (Exception er){
            throw  new Exception();
        }finally {
            ret=2000;
            a=30;
        }
        return 1;
    }

    public void add(){
        try {
            
        }catch (Exception e){
            throw new ArrayIndexOutOfBoundsException();
        }finally {
            
        }
    }
    
```

这也就是为什么在自定义java异常类的时候，通常使用RuntimeException作为自定义异常类的父类。在非controller层抛出异常无序显示声明抛出的异常，统一交给controller进行处理。



## Effective java异常篇

try -with-resource

在jdk1.7中引入try -with-resource 来对关闭资源的try catch finally 进行优化。对于某个多次打开某个资源的方法在代码中会产生嵌套try finally 语句，产生的问题是无法获得完整的Exception,每次执行完毕后只会保持最后一个返回的异常。所以引入try with resource 使得 代码更加简洁易懂，而已更加容易诊断。只需要关闭对象上实现AutoCloseable接口即可，大部分java核心库中的类和接口都实现了。此外try -with-resource 也可以和catch语句一起使用，返回特定的返回对象。



努力使得失败保持原子性

如果在方法执行过程中发生异常，努力使得操作对象保持原子性，即不会被修改

对此java中常用的几条建议以及在工程中常用的方法分别是

1. 使用不变对象
2. 在执行操作前检查参数的有效性提前抛出异常
3. 将可能有异常抛出的语句置前，将修改操作放置在可能发生异常语句后面 2的扩展
4. 创建一个临时对象，当完成
5. 在发生异常后执行回滚操作



## 项目开发中自定义异常的使用

在项目开发中会用到参数校验，无可避免的会出现许多if else 或者 异常捕获以及抛出的问题，通过统一异常处理处理可以很好的解决这个问题。使用Assert+自定义异常将程序中发生的异常全部抛出到controller层进行处理可以使得代码结构更加清晰，以及避免异常被吞掉。

整体思路如下：

1. 创建固定返回数据模板
2. 创建自定义异常类
3. 自定义断言异常类抛出自定义异常
4. 在controller层的操作模板中捕获异常并抛出

```java
//自定义返回结果实体类
public class Result<T> extends ToString {

    private static final long serialVersionUID = 8597086345883261973L;

    /**
     * 执行结果
     */
    private boolean success = false;

    /**
     * 是否需要重试
     */
    private boolean isRetry = false;

    /**
     * 错误码
     */
    private String errorCode;

    /**
     * 错误信息
     */
    private String errorMsg;

    /**
     * 数据
     */
    private T data;
    //构造方法 省去

```



```java
//自定义 异常类
public class BetahouseException extends RuntimeException {

    private static final long serialVersionUID = -2372085495406352289L;

    /**
     * 异常码
     */
    private String errorCode;

    /**
     * 异常信息
     */
    private String message;

    /**
     * 构造器
     *
     * @param cause
     */
    public BetahouseException(final Throwable cause) {
        super(cause);
        this.errorCode = CommonResultCode.SYSTEM_ERROR.getCode();
        this.message = CommonResultCode.SYSTEM_ERROR.getMessage();
    }
    public BetahouseException(String errorCode, String message) {
        this.errorCode = errorCode;
        this.message = message;
    }

    public BetahouseException(ResultCode resultCode) {
        this.errorCode = resultCode.getCode();
        this.message = resultCode.getMessage();
    }

    public BetahouseException(ResultCode resultCode, String message) {
        this.errorCode = resultCode.getCode();
        this.message = message;
    }

    public BetahouseException(Throwable cause, String errorCode, String message) {
        super(cause);
        this.errorCode = errorCode;
        this.message = message;
    }

```



```java
 //断言工具类的部分方法
	/**
     * 断言对象等于null
     *
     * @param obj
     * @param errorMsg
     */
    public static void assertNull(Object obj, String errorMsg) {
        if (obj != null) {
            throw new BetahouseException(CommonResultCode.ILLEGAL_PARAMETERS.getCode(), errorMsg);
        }
    }

    /**
     * 断言对象不等于null
     *
     * @param obj
     */
    public static void assertNotNull(Object obj) {
        if (obj == null) {
            throw new BetahouseException(CommonResultCode.ILLEGAL_PARAMETERS);
        }
    }
```

接下里就是如何在controller中如何实现统一处理异常如果使用@ControllerAdvice 则无法使用自定义返回实体类只能使用

ModelAndView对象
Model对象
Map对象
View对象
String对象
还有@ResponseBody、HttpEntity<?>或ResponseEntity<?>，以及void

所以这边借鉴切面定义了一个操作模板实现统一的异常捕获和处理。

```java
 public static <T> Result<T> operate(Logger logger, String methodName, Object request, RestOperateCallBack<T> callBack) {
        long start = System.currentTimeMillis();
        Result<T> result = null;
        try {
            //操作前置
            callBack.before();

            //执行操作
            result = callBack.execute();

            //操作后置
            callBack.after();
            return result;
        } catch (BetahouseException be) {
            LoggerUtil.warn(be, logger, "RestOperateTemplate.operate fail, methodName={0}, request={1}, errorCode={2}, errorMsg={3}", methodName, request, be.getErrorCode(), be.getMessage());
            result = new Result<>(false, convertCode(be.getErrorCode()), be.getMessage());
            return result;
        } catch (Exception e) {
            LoggerUtil.error(e, logger, "RestOperateTemplate.operate error, methodName={0}, request={1}", methodName, request);
            result = new Result<>(false, RestResultCode.SYSTEM_ERROR.getCode(), RestResultCode.SYSTEM_ERROR.getMessage());
            return result;
        } catch (Throwable t) {
            LoggerUtil.error(t, logger, "RestOperateTemplate.operate throwable, methodName={0}, request={1}", methodName, request);
            result = new Result<>(false, RestResultCode.SYSTEM_ERROR.getCode(), RestResultCode.SYSTEM_ERROR.getMessage());
            return result;
        } finally {
            long end = System.currentTimeMillis();
            LoggerUtil.info(logger, "RestOperateTemplate.operate final, methodName={0}, consume={1}ms, request={2}, result={3}", methodName, end - start, request, result);
        }
    }
```

> 参考资料
>
> [博客]([https://github.com/ZXZxin/ZXBlog/blob/master/Java/%E5%BC%82%E5%B8%B8/Java%E5%BC%82%E5%B8%B8%E6%80%BB%E7%BB%93.md](https://github.com/ZXZxin/ZXBlog/blob/master/Java/异常/Java异常总结.md))
>
> Effective java 第三版
>
> 码出规范：《阿里巴巴Java开发手册》
>
> β-house 第二课堂小程序

